title:              Bjegolovac
email:              bjegolovac@gmail.com
description:        Bjegolovac web
author:             Bjegolovac
baseurl:            "/"
url:                "https://bjegolovac.github.io"

# Social Profiles
twitter_username:   bjegolovac
github_username:    bjegolovac
facebook_username:  Bjegolovac
instagram_username:  bjegolovac
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
